### ISSUE TITLE
Add to disqus for blog comment

### ISSUE THREAD

**Issue by mrabdullahsahin** [mrabdullahsahin/mrabdullahsahin.github.io#4]

**Comment by VincentTam** [comment]
Hi, Disqus has a plethora of shortcomings that deter many bloggers, say

1. privacy issues
2. slow load speed
3. no markdown support
4. poor SEO
5. high cost of migration

Have you thought of using [Staticman](https://staticman.net/) for static blog comments?  Comments are stored as YML files inside your repo, so that you completely own the comment.  With a static blog generator, these YML files can be converted into HTML elements under your posts, so that the comments are SEO-friendly.

Here's a Gatsby-powered site powered by Staticman: https://github.com/robinmetral/eaudepoisson.

You may refer to these articles to know more.

1. https://victorzhou.com/blog/replacing-disqus/
1. https://old.reddit.com/r/programming/comments/b9022a/switching_off_of_disqus_reduced_my_page_weight_by/
1. https://medium.com/remys-blog/ejecting-disqus-4120e9985823
